oblador/loki

src/targets/native/configure-storybook.js

...by adding some retry logic. Numbers are arbitrary, please confirm it fixes your issue @Gongreg.

Fix race condition getting the addons channel in react-native

---

docs/getting-started.md
examples/react-native/android/app/build.gradle
examples/react-native/android/app/src/main/java/com/loki/MainApplication.java
examples/react-native/android/settings.gradle
examples/react-native/package.json
examples/react-native/yarn.lock
src/targets/native/configure-storybook.js

Builds on #20. Apparently `DevSettings` module isn't implemented on android, so use a polyfill for the time being.
@xaviervia

Android self-healing tests

---

docs/command-line-arguments.md
src/commands/test/default-options.json
src/commands/test/parse-options.js
src/commands/test/run-tests.js
src/targets/chrome/docker.js

In case you want a specific version of chrome or maybe use your own image etc. 
Related to #15, @derekstavis

Expose chrome headless docker image as config and CLI flag

---

package.json
src/targets/chrome/get-browser-globals.js
yarn.lock

Fix JSDOM environment

---

yarn.lock

It fixes some warnings on travis.
Shall we consider something like https://greenkeeper.io ?

Upgrade eslint and friends

---

docs/command-line-arguments.md
src/commands/test/default-options.json
src/commands/test/parse-options.js
src/targets/chrome/create-chrome-target.js

As discussed there: https://github.com/oblador/loki/pull/57

Add an option to retry failed tests

---

src/targets/chrome/docker.js

First of all, thanks for writing `loki`! I am excited to integrate it into my teams toolchain, and looking forward to helping to add features/fixes/etc as they arise.
One of the things that I ran into was that in my team, running `chrome.docker` works great locally, however, we run our Jenkins infrastructure as docker containers (each Jenkins agent is a docker container) so launching `chrome.docker` from Jenkins launches it as a `sibling` container, instead of our process being the host machine and the `chrome.docker` being a docker instance on our host exposing the `port` that we can talk to from `127.0.0.1`.
This PR should fix this problem, allowing the current behavior to work unchanged, however, detecting if the `loki` process is itself running in a docker container, and switching the …

Allow docker to run from sibling container

---

src/commands/test/get-absolute-url.js
src/commands/test/get-absolute-url.spec.js
src/commands/test/parse-options.js
src/targets/chrome/docker.js

Fixes https://github.com/oblador/loki/issues/80

Fix relative URLs not being resolved for chrome.app

---

src/commands/test/run-tests.js
src/targets/chrome/create-chrome-target.js
src/targets/chrome/docker.js

Fixes https://github.com/oblador/loki/issues/38

Add docker image download as a separate step

---

.npmignore
package.json

This decreases the tarball size to 25.8 kB from 795.0 kB
```
📦  loki@0.13.0
=== Tarball Contents === 
2.4kB   package.json                                                                                    
55B     configure-react-native.js                                                                       
61B     configure-react.js                                                                              
59B     configure-vue.js                                                                                
1.1kB   LICENSE                                                                                         
2.9kB   README.md                                                                                       
46B     bin/loki …
```

Remove fixtures and tests from npm bundle

---

src/targets/chrome/add-loki-session-marker.js
src/targets/chrome/create-chrome-target.js

https://github.com/oblador/loki/issues/109
https://github.com/oblador/loki/projects/1#card-5208258
With this update, I'm able to use  next code in styles 
```css
*[loki-test] .loki-invisible {
opacity: 0;
}
```
or from js:
```javascript
if (window._isLokiTest) {
// loki specific logic
}
```

Mark root element with attr

---

.travis.yml

Will enable us to run it in parallel to make it faster and easier to understand exactly what went wrong.

Split up travis into stages

---

.travis.yml

Shouldn't mix these types of conditions :-)

Fix Travis conditional deploy

---

src/cli.js
src/errors.js
src/targets/chrome/docker.js

Useful in cases like #94 where something is wrong but hard to debug why.

Improve errors when chrome fails to start in docker

---

packages/target-chrome-core/src/create-chrome-target.js

Introduced by https://github.com/oblador/loki/pull/170

Await window resize to fix race condition in tall content

---

docs/configuration.md
packages/runner/package.json
packages/runner/src/config/index.js

As requested by #203 et al. Will also enable more advanced setups, such as passing function arguments.

Support separate configuration file

---

packages/integration-core/src/decorate-storybook.js

According to [the docs](https://storybook.js.org/docs/formats/storiesof-api/#decorators-and-parameters), storybook supports a third parameter when calling `add`, to give story-level parameters (which can be options, config or parameters to send to decorators, for example).
Without this PR, it's not possible to pass parameters to a decorator when using lokiAsync. This PR enables that, and shouldn't cause a problem to eventually older storybook versiones that don't support that due to the nature of non-declared parameters in JavaScript ;)
Let me know what you think please

Add storiesOf parameters (third argument) support

---

.github/workflows/tests.yml
.gitignore
package.json
packages/renderer-aws-lambda/src/create-aws-lambda-renderer.spec.js
yarn.lock

Travis CI suddenly stopped reporting builds and has a [somewhat uncertain future](https://news.ycombinator.com/item?id=19218036). Plus Github Actions has the neat feature of annotations in the PR itself. 
Edit: Travis started working again without any changes on my side, but I'd rather have something that works every time and doesn't run the tests twice for PRs.

Add tests workflow

---

docs/getting-started.md
packages/loki/README.md

Remove version in node requirement

---

packages/runner/package.json
yarn.lock

Revert "Bump transliteration dependency"

---

.github/workflows/tests.yml
examples/react/package.json
packages/target-chrome-docker/src/create-chrome-docker-target.spec.js
test/cli/test-cra-init.sh

I'm somewhat new to the github actions thingie, and I made a boo-boo.

Run tests on PRs

---

packages/loki/package.json

Per instructions from this page: https://storybook.js.org/docs/react/addons/addon-catalog

Add meta data for Storybook Addon Catalog

---

packages/loki/README.md

Add development instructions to README

---

.github/workflows/website.yml

Fixes https://github.com/oblador/loki/pull/355#issuecomment-1079666872

Remove branch check from publish job

---

examples/react/src/api/Decorators.stories.js
packages/browser/src/get-stories.js
packages/integration-react-native/src/configure-storybook-react-native.js

Filter out circular parameters

---

packages/integration-react-native/src/configure-storybook-react-native.js

Broken due to changes in RN and Storybook APIs, this PR uses the current version of those which will potentially break installations stuck on old versions. Closes #381

Fix RN integration for recent versions

---

examples/react-native/package.json
examples/react-native/storybook/stories/Logo/index.js
examples/react/package.json
examples/react/src/async/Logo.js
packages/runner/src/commands/approve/parse-options.js
packages/runner/src/commands/test/parse-options.js
packages/target-chrome-docker/src/create-chrome-docker-target.js
packages/target-native-android-emulator/src/create-android-emulator-target.js
yarn.lock

It seems this proxy is now broken somehow, so this PR runs it locally instead which is a much better idea and less flaky.

Self-host deelay proxy

---

packages/loki/package.json

Resolves peer dep issue when using Loki with "@storybook/react" 7

chore: update storybook/react peer dep

---

packages/integration-react-native/package.json
yarn.lock

fix: add missing dependency [RN]

---

packages/target-chrome-docker/package.json
packages/target-chrome-docker/src/create-chrome-docker-target.js
yarn.lock

`wait-on` is a bit bloated using heavy dependencies, `wait-port` does the same thing but is leaner and w/o ESM issues.
Supersedes #493
Closes #493

Replace wait-on with wait-port
