docs/configuration.md
In the example the spelling is `skip-stories` (kebab-case) but the format is `skipStories` (camel-case).
=> Fix `skipStories` format in the documentation

src/targets/chrome/docker.js
closes #13 
With this change seccomp files are skipped from CI, but in your local environment seccomp will be used.
=> ci: skip seccomp on ci

examples/react-native/storybook/stories/ErrorThrowingComponent/index.js, examples/react-native/storybook/stories/index.js, src/errors.js, src/targets/native/configure-storybook.js, src/targets/native/create-message-queue.js, src/targets/native/create-websocket-target.js
Replaces default React Native crash handler and injects Loki instead to output errors thrown by the story to the terminal instead and automatically recover from the crash by reloading the app. 
As requested by @xaviervia
=> React native error handling

examples/react-native/ios/Loki/Info.plist, examples/react-native/storybook/stories/ErrorThrowingComponent/index.js, examples/react-native/storybook/stories/Logo/index.js, examples/react-native/storybook/stories/index.js, src/errors.js, src/targets/native/configure-storybook.js, src/targets/native/create-message-queue.js, src/targets/native/create-websocket-target.js, src/targets/native/ready-state-emitting-image.js, src/targets/native/ready-state-manager.js
* When an image fails to load on React Native, instead of taking a screenshot and get an obvious diff, fail the story fast and detail what went wrong in the output. 
* Add `setNativeProps` to `ReadyStateEmittingImage` to fix crash when it's wrapped with a `TouchableOpacity`.
* Bump image load timeout to 10s.
=> Improve native image handling

src/diffing/looks-same.js
Changing the `--chromeTolerance` was having an effect on the diff images, but not changing whether tests would pass or fail. This PR passes tolerance in as an option so that it will be used to determine matching.
=> Use tolerance when determining a match

src/targets/chrome/fetch-storybook-worker.js, src/targets/chrome/fetch-storybook.js, src/targets/chrome/get-browser-globals.js
@felquis reported in #29 that loki would sometimes fail with error `TypeError: source.close is not a function`. Upon some investigation the problem was in two parts: 
1. `EventSource` wasn't properly mocked, thus calling `close` on an instance would cause it to crash. 
2. Storybook running in sandboxed VM would includes some retry logic with timers causing the shutdown of the loki process to be slow as it was waiting for all code to execute. 
This PR tries to adress this by running the storybook bundle in a sub process instead and by mocking the `close` method too.
=> Run sandboxed storybook bundle in sub process

src/targets/chrome/fetch-storybook-worker.js
Fixes issue where loki would use the wrong script source when there's many of them and would resolve the URL incorrectly if external. Fixes https://github.com/oblador/loki/issues/39
=> Fix bundle script matcher and resolver

src/commands/test/run-tests.js
This most likely is a symptom of something going wrong, and should be considered an error.
=> Throw if no stories were found

src/targets/chrome/fetch-storybook-worker.js, src/targets/chrome/get-browser-globals.js
Based on @priomsrb's comment, fixes https://github.com/oblador/loki/issues/51.
Tried it out with latest versions of storybook and works great.
Weirdly enough, we are not getting the "No stories were found." error.
=> Add url to JSDOM constructor

docs/command-line-arguments.md, docs/configuration.md, src/commands/test/parse-options.js, src/commands/test/run-tests.js
The default Listr renderer doesn't play well with non-TTY outputs.
By passing `--verboseRenderer`, we configure Listr to use their `verbose` renderer, which though not fancy, works well on CI.
Feedback is welcome :)
=> Add option to configure Listr in verbose mode

src/diffing/gm.js
Got weird undescriptive errors like below due to a broken GM installation. Turns out the `gm` library returns strings and not errors, so Listr wouldn't output them properly.
=> Fix Listr not outputting gm errors

src/config/project-package.js
This was an issue for us because we moved what dependencies we had to be peer-dependencies, thus breaking this function.
=> Fixes hasReactNativeDependency() when the project has no dependencies in package.js

src/targets/chrome/docker.js
That helps to avoid crashes of the docker container, when the parallelism is high.
Should we maybe make it configurable, or would 1gb be ok for now?
=> Increase shared memory to 1gb

src/targets/decorate-storybook.js
Upgrading to a later version of storybook breaks skip/async methods, and this PR fixes that.
=> Fix storiesOf monkey patch

docs/command-line-arguments.md, docs/configuration.md, src/commands/test/default-options.json
**This is a breaking change**
If using docker screenshots are supposed to be as deterministic as possible, this setting should only be needed if you're using the chrome app on different platforms.
Related issue: https://github.com/oblador/loki/issues/69
=> Default chromeTolerance to be 0

src/cli.js
Fixes the **`[Object object]`** output after a request failed to load as shown in the screenshot in this issue: https://github.com/oblador/loki/issues/80
=> Fix final output of failed url loading errors

package.json, src/commands/test/test-story.js, src/commands/test/test-story.spec.js, yarn.lock
Current behaviour is to pass `loki test` locally when a test doesn't have a reference image, but fail it in CI. With this PR `loki test` will still pass, but also add a reference image. Behaviour in CI or with the `--requireReference` flag is unchanged. 
Fixes https://github.com/oblador/loki/issues/95
Bump of jest was needed for promise assertions.
=> Auto update missing references

package.json, src/targets/native/ready-state-emitting-image.js, yarn.lock
Currently using `Image.resolveAssetSource` is not possible as the ready state emitting Image monkey patch does not re-export it.
This resolves this issue.
=> Maintain access to resolveAssetSource after monkey-patch

src/targets/chrome/create-chrome-target.js, src/targets/chrome/get-selector-box-size.js
In some edge cases we filter out elements matching the selector and thus can't determine a size. Currently it fails with the cryptic `Reduce of empty array with no initial value`. This PR changes this to a more user friendly error message as well as another edge case where `isNotWrapperElement` would not take invisible elements into consideration.
=> Fix "Reduce of empty array with no initial value" when elements are invisible

docs/command-line-arguments.md, src/commands/test/parse-options.js, src/commands/test/run-tests.js, src/targets/chrome/docker.js
Unfortunately in our Jenkins CI we are restricted an only able to run `docker` commands with `sudo`, because of this loki is unable to run with the `chrome.docker` target.
This PR adds a `dockerAsSudo` option to resolve this, it'll run all `docker` commands with `sudo` prepended if the option has been specified.
More than happy to take feedback & answer any questions!
=> Add option to run docker commands with sudo

src/cli.js, src/failure-handling.js, src/targets/chrome/create-chrome-target.js, src/targets/chrome/create-chrome-target.spec.js
I get an intermittent `Socket hang up` error when fetching stories from storybook, there's no real pattern to it and it happens on all versions of chrome that I tested, but maybe 1% of the time. There's a few [long standing issues reported in CDP](https://github.com/cyrus-and/chrome-remote-interface/issues/58) but they go nowhere as it's hard to reproduce. 
This PR takes the a bit lazy pragmatic approach of adding a few retries to this function. I'm unsure if this is enough to resolve it, but time will tell :-)
=> Add retries to chrome getStorybook

src/targets/chrome/docker.js
During: https://github.com/oblador/loki/commit/d5215172d2da54a8774b25094281d120a7f77cd8#diff-b75c1e1e6b0fa125e76a9f03fe7716c5R167 an error has been made and `execute` is not passed anymore to `getNetworHost` function which causes an error like below:
This PR should fix this issue.
=> Fix issue with lack of execute

.travis.yml
I'm not sure why this started failing all of a sudden, but most likely due to some breaking change in Travis. Should probably move away from it eventually given recent events.
=> Fix Travis: Run example installation before script instead of before install

examples/react/src/Logo.js
This was due to the docs revamp.
=> Fix loki logo URL in visual tests

packages/runner/src/commands/test/parse-options.js
Hi!
It seems #127 had a bug when it was merged. 
The docs say the config parameter in `package.json` should be `looks-same` (https://github.com/oblador/loki/blame/master/docs/configuration.md#L48), but currently that's not what gets read.
[Here](https://github.com/oblador/loki/blame/master/docs/configuration.md#L48) it's reading `looksSame` instead of `looks-same`, and storing it as a key `looksSame` also in the parsed configuration.
Later, when creating the diffing engine [here](https://github.com/oblador/loki/blob/master/packages/runner/src/commands/test/test-story.js#L49-L52), the it tries to get a config key with the same name as the `diffingEngine` given, which is never `looksSame`, but instead is either `gm` or `looks-same`. As a result, the config for `looks-same` never gets passed …
=> Fix looks-same config params reading

docs/configuration.md, packages/runner/src/commands/test/compare-screenshot.js, packages/runner/src/commands/test/parse-options.js
Thanks to the new non-JSON based config support, we're able to take a custom file name formatter as a config option. 
Fixes #164, #165, #208.
=> Add fileNameFormatter config

packages/target-chrome-docker/src/create-chrome-docker-target.js
When there's an error starting Chrome I get:
`FAIL chrome.docker/START: Cannot read property 'length' of null`
instead of the actual error message.
Not sure if there was a reason to set errorMessages to null, but this fixes the problem.
=> don't clear error logs.

packages/loki/bin/loki, packages/loki/package.json
With the monorepo restructuring the binary was moved to a subpackage, which seems to cause warnings/errors when installing globally as outlined in #221. 
This PR adds it back to the main `loki` package as an alias to the `runner` package.
=> Add loki command alias to entry package

packages/target-chrome-core/src/create-chrome-target.js
This fixes a common failure when doing `loki` on CircleCI. 
Over 100 runs:
* 100 times would fail the first time (caught by the `withRetries(2`)
* 90 times would work the second time
* 10 times it would fail the second time
This tries to fix 10% of the cases. 
Over the last 2 weeks we have been testing this patch (> 200 builds) and have had ZERO failures!
=> Wait between retries when launching stories tab.

docs/configuration.md, examples/react/loki.config.js, examples/react/package.json
Moved the configuration for the React example to a separate file 'loki.config.js' in order to showcase the option of a separated config file
=> Edit react example to showcase loki.config.js usage

packages/browser/src/await-selector-present.js, packages/browser/src/index.js, packages/target-chrome-core/src/create-chrome-target.js
For very large bundles/slow components, the rendering of the component can take a long while and since fonts are loaded first when they are needed to render some text, the current request stabilisation strategy doesn't work. 
This PR changes the behaviour to listen to requests to finish until the element we want to screenshot is present.
=> Listen to requests until selector is present

packages/integration-react-native/src/configure-storybook-react-native.js
It appears that the `global.loki` check added in #246 is incorrect and should instead be trying to create the `global.loki` only if it's not already defined.
This is currently causing a error preventing React Native tests from running at all as the line immediately after the if statement will try and assign `global.loki.isRunning = true;` while `global.loki` is undefined.
=> Fix loki global check for React Native

packages/renderer-aws-lambda/package.json, packages/runner/src/commands/test/compare-screenshot.js, packages/runner/src/commands/test/create-baseline-limited-batch-builder.js, packages/runner/src/commands/test/create-baseline-limited-batch-builder.spec.js, packages/runner/src/commands/test/get-output-paths.js, packages/runner/src/commands/test/run-tests.js, packages/runner/src/commands/test/task-runner.js
Sometimes stories with very large images can cause the lambda payload limits to be exceeded when batched together. Instead of lowering the size of all batches which would make execution slightly slower and more expensive, this PR makes an estimation of how many stories can fit into a batch based on the size of existing baselines.
=> Prevent lambda batches from exceeding payload limits

examples/react/.storybook/preview.js, examples/react/src/stories/index.stories.js, packages/browser/src/configure-storybook.js
#261 caused a regression for stories using `lokiAsync` that would cause it to time out, due to two instances of the ready state manager. 
I want to remove these eventually, but let's unbreak it for now.
=> Fix lokiAsync regression

packages/runner/package.json, yarn.lock
`npm audit` fails with
```
=== npm audit security report ===
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Prototype Pollution                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package …
```
=> Bump transliteration dependency

packages/diff-graphics-magick/package.json, packages/diff-graphics-magick/src/create-graphics-magick-differ.js
Here is no contributing guide, so I don't know how to format Pull Request, which steps I need to do to check my changes and I don't know how to test this changes properly.
GraphicsMagick's compare method checks only pixel diff in first image dimensions. This means that if second image is first image concated with another image, GM will decide that the images are equal.
In practice it means, that than I, as programmer, add some content to existing component/story, GM will not report any diff and Loki.js tests will pass. 
Check images dimensions manually. That method I use in current job project and it works.
=> Fix graphicsMagick comparing images with different dimensions. Fixes #44

packages/diff-looks-same/src/create-looks-same-differ.js, packages/diff-looks-same/src/create-looks-same-differ.spec.js
This PR is a partial fix for https://github.com/oblador/loki/issues/229. It creates the output diff folder immediately before asking looks-same to create a diff file. Because it only creates the folder when a diff file is going to be created, it does not create any empty folders.
This patch only applies to the looks-same differ. The Graphics Magic differ creates diff files even when there are no differences, so it needs to be fixed in a different way.
=> Allow slashes in diff paths with looks-same

packages/browser/src/get-storybook-error.js, packages/browser/src/index.js, packages/target-chrome-core/src/create-chrome-target.js
Currently loki will fail either by not returning any stories or by saying timed out waiting for selector when in fact the story is throwing a render error. This can be a bit confusing if running in CI or not working in storybook while running the tests. This PR will present the render error from storybook to the user instead.
=> Surface render errors to user

docs/command-line-arguments.md, packages/runner/src/cli.js, packages/runner/src/commands/test/parse-options.js, packages/runner/src/commands/test/renderers/index.js, packages/runner/src/commands/test/renderers/non-interactive.js, packages/runner/src/commands/test/renderers/silent.js, packages/runner/src/commands/test/run-tests.js
For large test suites the default non-interactive logger can be quite noisy and making it hard to find the actual error. To solve these cases, this PR adds a `--silent` flag that will only output error messages.
=> Add silent flag

packages/integration-react/package.json, packages/loki/package.json
Tested with storybook 6 and it's working great.
Adding storybook 6 in our peerDependencies list.
also `loki` claims `@loki/integration-react` as its dependencies, we would have to decalre optional peerDepndnecies for `loki` as well.
=> add storybook 6 in peerDependencies list

packages/target-chrome-docker/src/get-network-host.js
In 5ab26d6a5ea5bba33f31ff7f20f05c60b0d37b13 you bumped the version of execa from 1.0.0 to 5.0.0 and also updated the extraction from `code` to `exitCode` but you missed one place :)
=> Adapt missing code to exitCode extraction after execa version bump

packages/target-chrome-docker/src/create-chrome-docker-target.js
Since wait-on >= 5.2, the error message has been changed from `Timeout` to `Timed out waiting for`:
https://github.com/jeffbski/wait-on/blob/3f3bd9544fd320665eff1975f0ad0a059107471d/lib/wait-on.js#L25
=> fix: compare with new correct error message from waitOn

.github/workflows/tests.yml
As requested in https://github.com/oblador/loki/pull/353#issuecomment-1001339392
- fixes https://github.com/oblador/loki/runs/4620140217
- unblocks https://github.com/oblador/loki/pull/352
The last build failed ❌ because one of the dependencies doesn't support Node.js 12.x
🔗 https://github.com/oblador/loki/runs/4620140217
=> Use Node.js 14 for CLI integration tests in GitHub Actions

packages/target-chrome-app/package.json, yarn.lock
This fixes an issue where chrome would fail to launch if `localhost` resolved to the IPv6 address `::1` on Node 17.
Fixes #369.
=> Upgrade chrome-launcher dependency

docs/command-line-arguments.md, packages/runner/src/commands/test/parse-options.js, packages/runner/src/commands/test/run-tests.js, packages/target-native-android-emulator/package.json, packages/target-native-android-emulator/src/create-android-emulator-target.js, packages/target-native-ios-simulator/package.json, packages/target-native-ios-simulator/src/create-ios-simulator-target.js
Currently when running loki on a machine with multiple iOS simulators, loki will use the first booted device to use for screenshots.
In our CI we run 3 side-by-side iOS simulators on each machine which results in screenshots being captured from the incorrect simulator.
This PR adds a new `--device` flag to loki which allows you to specify the device ID to use for screenshots. We've [forked osnap](https://github.com/ferocia/osnap) which is no longer maintained and [added support for selecting a device ID for iOS](https://github.com/ferocia/osnap/pull/1). It already had support for Android.
I know there was some dicussion about proper concurrency support in #71, but given the age of that issue I assume there hasn't been any progress in that space.
=> Add support for targetting a specific device ID when running in React Native

packages/target-native-android-emulator/src/create-android-emulator-target.js, packages/target-native-ios-simulator/src/create-ios-simulator-target.js, yarn.lock
Sorry @oblador, I accidentally missed these changes from #427
Was still targetting the old deprecated `osnap` package.
=> Update osnap target to @ferocia-oss/osnap

packages/target-chrome-app/package.json, packages/target-chrome-docker/package.json, yarn.lock
@techeverri
Closes: #405 
This PR fixes the `ECONNREFUSED` error when using `loki` with Node 17+ described in #405.
DNS lookup returns IPv6 with Node 17+, which breaks the `chrome-remote-interface` initialization. However, this problem was fixed in a newer version of the `chrome-remote-interface` package, so updating the package solved the issue for me.
=> Update chrome-remote-interface to fix connection problem with Node 18

packages/target-chrome-app/package.json, packages/target-chrome-docker/package.json, yarn.lock
Update `chrome-remote-interface` to version 0.32.1 to resolve https://github.com/oblador/loki/issues/442
=> Update chrome-remote-interface to resolve DevTools connection issue

packages/browser/src/get-stories.js, packages/runner/src/commands/test/default-options.json
This adds support for the new format of stories in storybook 7.
It fixes #436 with a solution proposed by @AleksRap.
As far as I see this should also be backwards compatible with older storybook versions.
=> Add storybook 7 support

packages/target-native-android-emulator/package.json, packages/target-native-ios-simulator/package.json, yarn.lock
`@ferocia-oss/osnap` received some sub-dependency updates in 1.3.1 which resolved some outstanding security issues and CVEs, unfortunately some of these updates included some packages which have moved exclusively to ES Modules which broke in Common JS environments.
This has been fixed as of 1.3.5, the broken versions have been deprecated on NPM, however to help other developers avoid ending up with a bas version I figured it'd be good to bump the required version of `@ferocia-oss/osnap` in the `package.json`
Fixes #448
Fixes #447
=> Update @ferocia-oss/osnap to fix issues with ES Modules

packages/runner/src/commands/test/parse-options.js, packages/runner/src/commands/test/run-tests.js, packages/target-chrome-docker/package.json, packages/target-chrome-docker/src/create-chrome-docker-target.js, packages/target-chrome-docker/src/create-static-server.js, yarn.lock
With Storybook 7 some files can no longer be served via `file:` protocol because it throws CORS errors. This PR fixes that by starting a local http server that serves those files instead. 
Fixes #446, #460
=> Use http server for file references

docs/configuration.md
At the moment, the link to react example is missing in the docs. I added this link https://github.com/oblador/loki/tree/master/examples/react to the configuration file
=> Add link to React example in docs/configuration.md

packages/target-chrome-docker/src/create-chrome-docker-target.js
Previously the unit tests used `latest` which caused them to suddenly fail because Chrome is crashing. Long term we would probably want to investigate why latest version is crashing (if it's an issue with the docker image or with the GitHub Action environment).
=> Lock Chrome version in docker tests

packages/target-chrome-app/package.json
=> Add missing core dependency to target-chrome-app

packages/integration-react/package.json
This should solve issue with the following warnings observed when installing `loki`:
```
npm install --save-dev loki
npm WARN ERESOLVE overriding peer dependency
npm WARN While resolving: @loki/integration-react@0.33.0
npm WARN Found: @storybook/react@7.5.2
npm WARN node_modules/@storybook/react
npm WARN   dev @storybook/react@"^7.5.2" from the root project
npm WARN   3 more (@storybook/preset-react-webpack, ...)
npm WARN 
npm WARN Could not resolve dependency:
npm WARN peerOptional @storybook/react@"^5 || ^6" from @loki/integration-react@0.33.0
npm WARN node_modules/loki/node_modules/@loki/integration-react
npm WARN   @loki/integration-react@"^0.33.0" from loki@0.33.0
npm WARN   node_modules/loki
npm WARN 
npm WARN Conflicting peer dependency: @storybook/react@6.5.16
npm WARN …
```
=> Update @storybook/react peer dependency in @loki/integration-react

packages/browser/src/get-stories.js
This PR enables loki on Storybook 8. 
It only fixes the API calls required but doesn't challenge the core concepts which rely on `storyStore.raw()`. That is still deprecated and will be gone for Storybook 9.
fixes #503
=> Fix - Make loki work with Storybook8

packages/create-async-callback/package.json
When installing `@loki/create-async-callback` from npm its [types](https://github.com/oblador/loki/blob/master/packages/create-async-callback/index.d.ts) are not included in the package.
Similar to this [previous PR](https://github.com/oblador/loki/pull/500) for `@loki/is-loki-running` this PR ensures the types are included in the package by adding  `*.d.ts` to the `files` in the `package.json`.
=> Fix: ensure types are included for create-async-callback package
